[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/.netlify/functions/viewer"
  to = "/.netlify/functions/viewer"
  status = 200
  force = true

[[redirects]]
  from = "/viewer"
  to = "/.netlify/functions/viewer"
  status = 200
  force = true

[[redirects]]
  from = "/viewer/*"
  to = "/.netlify/functions/viewer"
  status = 200
  force = true
